/* =====================================================
   QUERY 1
   Average views grouped by trust rating
===================================================== */

EXPLAIN ANALYZE

SELECT
    ls.avg_rating,
    SUM(ds.views) AS total_views

FROM listing_stats ls

JOIN demand_signals ds
ON ls.listing_id = ds.listing_id

GROUP BY ls.avg_rating

ORDER BY ls.avg_rating;



/* =====================================================
   QUERY 2
   Revenue generated by listing category
===================================================== */

EXPLAIN ANALYZE

SELECT
    c.category_name,
    SUM(t.price_paid) AS total_revenue

FROM transactions t

JOIN listings l
ON t.listing_id = l.listing_id

JOIN categories c
ON l.category_id = c.category_id

GROUP BY c.category_name

ORDER BY total_revenue DESC;



/* =====================================================
   QUERY 3
   Revenue by trust level
===================================================== */

EXPLAIN ANALYZE

SELECT

    CASE
        WHEN avg_rating >= 4.5 THEN 'Excellent'
        WHEN avg_rating >= 4.0 THEN 'Good'
        WHEN avg_rating >= 3.0 THEN 'Average'
        ELSE 'Poor'
    END AS trust_level,

    SUM(total_sales) AS total_sales

FROM listing_stats

GROUP BY trust_level

ORDER BY total_sales DESC;